---
kind: pipeline
name: linux-amd64-latest

platform:
  arch: amd64
  os: linux

services:
- name: broker
  image: eclipse-mosquitto

steps:
- name: run tests
  image: alpine:3.12
  commands:
  - apk add --no-cache python3 py3-pip
  - cp -r /drone/src /tmp/src
  - pip3 install --no-cache-dir -r /tmp/src/requirements.txt
  - pip3 install --no-cache-dir behave
  - mv /tmp/src/config.tests.toml /tmp/src/config.toml
  - cd /tmp/src && python3 -m behave

- name: build docker image
  image: plugins/docker
  settings:
    repo: svedrin/mqtt-pushgateway
    tags: latest-amd64
    username: svedrin
    password:
      from_secret: docker-registry-pw
    cache_from: "svedrin/mqtt-pushgateway:latest"
  when:
    branch: master
    event:
      exclude:
      - pull_request

---
kind: pipeline
name: linux-armv7l-latest

platform:
  arch: arm
  os: linux

steps:
- name: build docker image
  image: plugins/docker
  settings:
    repo: svedrin/mqtt-pushgateway
    tags: latest-armv7l
    username: svedrin
    password:
      from_secret: docker-registry-pw
    cache_from: "svedrin/mqtt-pushgateway:latest"

trigger:
  branch: master
  event:
    exclude:
    - pull_request

depends_on:
- linux-amd64-latest

---
kind: pipeline
type: docker
name: manifest-latest

steps:
- name: publish
  image: plugins/manifest:1.2
  settings:
    ignore_missing: true
    spec: docker-manifest-latest.tmpl
    username: svedrin
    password:
      from_secret: docker-registry-pw

trigger:
  branch: master
  event:
    exclude:
    - pull_request

depends_on:
- linux-amd64-latest
- linux-armv7l-latest


---
kind: signature
hmac: a2af1e4e6adbfb0038fcec45c67b75bd2d222631cc64bab1a04201c4a3589fe7

...
